src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 * @Vich\Uploadable

 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity=Peinture::class, mappedBy="categorie")
     */
    private $peintures;

    /**
     * @Vich\UploadableField(mapping="peinture_images", fileNameProperty="file")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="categories")
     */
    private $user;

    public function __construct()
    {
        $this->peintures = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Peinture[]
     */
    public function getPeintures(): Collection
    {
        return $this->peintures;
    }

    public function addPeinture(Peinture $peinture): self
    {
        if (!$this->peintures->contains($peinture)) {
            $this->peintures[] = $peinture;
            $peinture->addCategorie($this);
        }

        return $this;
    }

    public function removePeinture(Peinture $peinture): self
    {
        if ($this->peintures->removeElement($peinture)) {
            $peinture->removeCategorie($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function setImageFile(?File $file = null): void
    {
        $this->imageFile = $file;

        if (null !== $file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->createdAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\BlogpostRepository;
use App\Repository\PeintureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(PeintureRepository  $peintureRepository, BlogpostRepository  $blogpostRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'peintures' => $peintureRepository->lastTree(),
            'blogposts' => $blogpostRepository->lastTree(),
        ]);
    }
}

templates/home/blogpost.html.twig
<!-- ARTICLES -->
<section class="pb-8 pt-mb-11 pt-md-10">

    <div class="container">
        <div class="row">
            <div class="col-12">

                <!-- Heading -->
                <h3 class="mb-0">
                    Dernières actualités
                </h3>

                <!-- Text -->
                <p class="mb-5 text-muted">
                    Here’s what we've been up to recently.
                </p>

            </div>

        </div> <!-- / .row -->
        <div class="row">
{% for blogpost in blogposts %}
            <div class="col-12 col-lg-4 d-flex">

                <!-- Card -->
                <div class="card shadow-light-lg lift lift-lg" data-aos="fade-up" data-aos-delay="100">

                    <!-- Image -->
                    <a class="card-img-top" href="{{ path('actualites_details', {'slug': blogpost.slug}) }}">

                        <!-- Image -->
                        <img src="{{ vich_uploader_asset(blogpost, 'imageFile') }}" alt="..." class="card-img-top">

                        <!-- Shape -->
                        <div class="position-relative">
                            <div class="shape shape-bottom shape-fluid-x text-white">
                                <svg viewBox="0 0 2880 480" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2160 0C1440 240 720 240 720 240H0v240h2880V0h-720z" fill="currentColor"/></svg>                  </div>
                        </div>

                    </a>

                    <!-- Body -->
                    <a class="card-body my-auto" href="#!">

                        <!-- Heading -->
                        <h3 class="mt-auto">
                            {{ blogpost.titre }}
                        </h3>

                        <!-- Text -->
                        <p class="mb-0 text-muted">
                            {{ blogpost.contenu|u.truncate(150,'...', false) }}
                        </p>

                    </a>

                    <!-- Meta -->
                    <a class="card-meta " href="#!">

                        <!-- Divider -->
                        <hr class="card-meta-divider">

                        <!-- Date -->
                        <p class="h6 text-uppercase text-muted mb-0 ms-auto">
                            <time datetime="2019-05-02">Publiée le {{ blogpost.createdAt|date('d/m/Y') }}</time>
                        </p>

                    </a>

                </div>

            </div>
            {% endfor %}

        </div> <!-- / .row -->
    </div> <!-- / .container -->
</section>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil!{% endblock %}



{% block body %}

    {% include 'home/welcome.html.twig' %}
    {% include 'home/realisations.html.twig' %}
    {% include 'home/blogpost.html.twig' %}



{% endblock %}

templates/home/realisations.html.twig
<!-- ARTICLES -->
<section class="pt-8 pt-md-11">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <!-- Heading -->
                <h2 class="mb-0">
                    Dernières réalisations
                </h2>

                <!--  -->
                <p class="mb-5 text-muted">
                    These span the grid's entire width with several options.
                </p>

            </div>
        </div> <!-- / .row -->
        <div class="row">
            {% for peinture in peintures %}
            <div class="col-12">

                <!-- Card -->
                <div class="card card-row shadow-light-lg mb-6 lift lift-lg" data-aos="fade-right" data-aos-delay="100">
                    <div class="row gx-0">
                        <div class="col-12">


                        </div>
                        <a class="col-12 col-md-6 order-md-2 bg-cover card-img-end" style="background-image: url({{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('miniature') }});" href="{{path('peintures_details', {'slug': peinture.slug} ) }}">

                            <!-- Image (placeholder) -->
                            <img src="{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('miniature') }}" alt="..." class="img-fluid d-md-none invisible">

                            <!-- Shape -->
                            <div class="shape shape-start shape-fluid-y text-white d-none d-md-block">
                                <svg viewBox="0 0 112 690" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h62.759v172C38.62 384 112 517 112 517v173H0V0z" fill="currentColor"/></svg>                  </div>

                        </a>
                        <div class="col-12 col-md-6 order-md-1">

                            <!-- Body -->
                            <a class="card-body" href="{{path('peintures_details', {'slug': peinture.slug} ) }}">

                                <!-- Heading -->
                                <h3>
                                    {{ peinture.nom }}
                                </h3>

                                <!-- Text -->
                                <p class="mb-0 text-muted">
                                    {{ peinture.description|u.truncate(150,'...', false) }}
                                </p>

                            </a>

                            <!-- Meta -->
                            <a class="card-meta" href="#!">

                                <!-- Divider -->
                                <hr class="card-meta-divider">

                                <!-- Date -->
                                <p class="h6 text-uppercase text-muted mb-0 ms-auto">
                                    <time datetime="2019-05-31">Ajoutée le {{ peinture.DateRealisation|date('d/m/Y') }}</time>
                                </p>

                            </a>

                        </div>

                    </div> <!-- / .row -->
                </div>

            </div>
            {% endfor %}
        </div> <!-- / .row -->
    </div> <!-- / .container -->
</section>

templates/home/welcome.html.twig
{% block body %}

    <!-- WELCOME -->
    <section data-jarallax data-speed=".8" class="py-10 py-md-14 overlay overlay-black overlay-60 bg-cover jarallax" style="background-image: url({{ asset('/img/Fond_donkey.jpg') | imagine_filter('welcome') }});">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-10 col-lg-8 text-center">

                    <!-- Heading -->
                    <h1 class="display-2 text-white">
                        Monkiz
                    </h1>

                    <!-- Text -->
                    <p class="lead text-white-75 mb-6">
                        Artiste Street Art
                    </p>

                    <!-- Button -->
                    <a href="{{ path('portfolio') }}" class="btn btn-primary lift">
                        Découvrir Portfolio
                        <i class="fe fe-arrow-right ms-3"></i>
                    </a>

                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>

    <!-- SHAPE -->
    <div class="position-relative">
        <div class="shape shape-bottom shape-fluid-x text-light">
            <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"/></svg>      </div>
    </div>

{% endblock %}