src/Entity/Peinture.php
<?php

namespace App\Entity;

use App\Repository\PeintureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PeintureRepository::class)
 * @Vich\Uploadable
 */
class Peinture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $largeur;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $hauteur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $EnVente;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateRealisation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $portfolio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @Vich\UploadableField(mapping="peinture_images", fileNameProperty="file")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="peintures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Categorie::class, inversedBy="peintures")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="peinture")
     */
    private $commentaires;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLargeur(): ?string
    {
        return $this->largeur;
    }

    public function setLargeur(?string $largeur): self
    {
        $this->largeur = $largeur;

        return $this;
    }

    public function getHauteur(): ?string
    {
        return $this->hauteur;
    }

    public function setHauteur(?string $hauteur): self
    {
        $this->hauteur = $hauteur;

        return $this;
    }

    public function getEnVente(): ?bool
    {
        return $this->EnVente;
    }

    public function setEnVente(bool $EnVente): self
    {
        $this->EnVente = $EnVente;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateRealisation(): ?\DateTimeInterface
    {
        return $this->dateRealisation;
    }

    public function setDateRealisation(?\DateTimeInterface $dateRealisation): self
    {
        $this->dateRealisation = $dateRealisation;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPortfolio(): ?bool
    {
        return $this->portfolio;
    }

    public function setPortfolio(bool $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function setImageFile(?File $file = null): void
    {
        $this->imageFile = $file;

        if (null !== $file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->createdAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setPeinture($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPeinture() === $this) {
                $commentaire->setPeinture(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

}

src/Controller/PeinturesController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Peinture;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use App\Repository\PeintureRepository;
use App\Service\CommentaireService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PeinturesController extends AbstractController
{
    /**
     * @Route("/peintures", name="peintures")
     */
    public function realisations(PeintureRepository $peintureRepository,
    PaginatorInterface $paginator,
     Request $request
    ): Response {
        $data = $peintureRepository->findBy([], ['id'=>'DESC']);
        $peintures = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            6
        );
        return $this->render('peintures/index.html.twig', [
            'peintures' => $peintures
        ]);
    }

    /**
     *@Route("/peintures/{slug}", name="peintures_details")
     */
    public function details(Peinture $peinture,
    Request $request,
    CommentaireRepository $commentaireRepository,
    CommentaireService $commentaireService
    ) : Response {

        $commentaires = $commentaireRepository->findCommentaires($peinture);
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire = $form->getData();
            $commentaireService->persistCommentaire($commentaire, null, $peinture);

            return $this->redirectToRoute('peintures_details', ['slug' => $peinture->getSlug()]);
        }

        return $this->render('peintures/details.html.twig', [
        'peinture'     => $peinture,
        'form'         => $form->createView(),
        'commentaires' => $commentaires,
            ]);
    }
}

templates/peintures/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails{% endblock %}
{% block body %}

<!-- CONTENT -->
<div class="container">
    <div class="row justify-content-between">
        <div class="col-12 col-md-4 position-md-sticky d-flex align-items-center vh-md-100" style="top: 0;">

            <!-- Sidebar -->
            <aside class="py-8 py-md-10">

                <!-- Brand -->
                <div class="img-fluid mb-4 text-body" style="max-width: 140px;">
                   <h1 style="text-transform: uppercase;">{{ peinture.nom }}</h1>
                </div>

                <!-- Text -->
                <p class="fs-lg mb-7 text-muted">
                     {{ peinture.description }}
                </p>

                <!-- List group -->
                <ul class="list-group list-group-flush">
                    {% for categorie in peinture.categorie %}
                    <li class="list-group-item">
                        <!-- Heading -->
                        <h6 class="d-flex mb-0 text-uppercase">
                            Catégorie <span class="ms-auto">{{ categorie.nom}}</span>
                        </h6>
                    </li>
                    {% endfor %}

                    <li class="list-group-item">
                        <!-- Heading -->
                        <h6 class="d-flex mb-0 text-uppercase">
                            Date de réalisation <span class="ms-auto">{{ peinture.dateRealisation|date('d/m/Y') }}</span>
                        </h6>
                    </li>

                    <li class="list-group-item">
                        <!-- Heading -->
                        <h6 class="d-flex mb-0 text-uppercase">
                            Largeur <span class="ms-auto">{{ peinture.largeur }} cm</span>
                        </h6>
                    </li>

                    <li class="list-group-item">
                        <!-- Heading -->
                        <h6 class="d-flex mb-0 text-uppercase">
                            Hauteur <span class="ms-auto">{{ peinture.hauteur }} cm</span>
                        </h6>
                    </li>

                    {% if peinture.enVente %}
                    <li class="list-group-item">
                        <!-- Heading -->
                        <h6 class="d-flex mb-0 text-uppercase">
                            <strong>Disponible à la vente</strong>
                            <span class="ms-auto">{{ peinture.prix }}€</span>
                        </h6>
                    </li>
                    {% endif %}


                </ul>

            </aside>

        </div>
        <div class="col-12 col-md-7">

            <!-- Images -->
            <section class="pb-8 pt-md-12 pb-md-10">
                <a class="d-block" data-bigpicture='{"imgSrc": "{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('full') }}" }' href="#">
                    <img class="img-fluid rounded" src="{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('full') }}" alt="...">
                </a>
            </section>

        </div>
    </div>
</div>

<!-- SHAPE -->
<div class="position-relative">
    <div class="shape shape-bottom shape-fluid-x text-light">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"/></svg>      </div>
</div>
    {% include "commentaire/form.html.twig" %}
    {% include "commentaire/commentaires.html.twig" %}
{% endblock %}

templates/peintures/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réalisations!{% endblock %}
{% block body %}

    <section class="pt-7 pt-md-10">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Heading -->
                    <h3 class="mb-0">
                        Popular Stories
                    </h3>

                    <!-- Text -->
                    <p class="mb-5 text-muted">
                        Here’s what’s big in the past week!
                    </p>

                </div>
            </div> <!-- / .row -->
            <div class="row">
                {% for peinture in peintures %}

                <div class="col-12 col-md-6 d-flex">

                    <!-- Card -->
                    <div class="card mb-6 shadow-light-lg lift lift-lg">

                        <!-- Image -->
                        <a class="card-img-top" href="{{ path('peintures_details', {'slug': peinture.slug}) }}">

                            <!-- Image -->
                            <img src="{{ vich_uploader_asset(peinture, 'imageFile') | imagine_filter('miniature') }}" alt="..." class="card-img-top">

                            <!-- Shape -->
                            <div class="position-relative">
                                <div class="shape shape-bottom shape-fluid-x text-white">
                                    <svg viewBox="0 0 2880 480" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2160 0C1440 240 720 240 720 240H0v240h2880V0h-720z" fill="currentColor"/></svg>                  </div>
                            </div>

                        </a>

                        <!-- Body -->
                        <a class="card-body" href="#!">

                            <!-- Heading -->
                            <h3>
                                {{ peinture.nom }}
                            </h3>

                            <!-- Text -->
                            <p class="mb-0 text-muted">
                                {{ peinture.description|u.truncate(150,'...', false) }}
                            </p>

                        </a>

                        <!-- Meta -->
                        <a class="card-meta mt-auto" href="#!">

                            <!-- Divider -->
                            <hr class="card-meta-divider">

                           {#  <!-- Avatar -->
                            <div class="avatar avatar-sm me-2">
                                <img src="assets/img/avatars/avatar-1.jpg" alt="..." class="avatar-img rounded-circle">
                            </div>

                            <!-- Author -->
                            <h6 class="text-uppercase text-muted me-2 mb-0">
                                Ab Hadley
                            </h6>
                           #}
                            <!-- Date -->
                            <p class="h6 text-uppercase text-muted mb-0 ms-auto">
                                <time datetime="2019-05-31">Ajoutée le {{ peinture.DateRealisation|date('d/m/Y') }}</time>
                            </p>

                        </a>

                    </div>

                </div>




                {% endfor %}

            </div> <!-- / .row -->
        </div> <!-- / .container -->
        <div class="d-flex justify-content-center">
            {% do peintures.setPageRange(2) %}
            {{ knp_pagination_render(peintures, 'base/pagination.html.twig') }}
        </div>
    </section>
{% endblock %}